import streamlit as st  # type: ignore
import pandas as pd
import time
import os
import pickle
import sys

# Ensure we can import from utils
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from utils.feature_extractor import extract_all_features  # type: ignore

# Base references
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FEATURES_PATH = os.path.join(BASE_DIR, "data", "features.csv")

# --- Setup Dashboard Configuration ---
st.set_page_config(
    page_title="Muon Physics Pipeline",
    page_icon="⚛️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- Custom CSS for Styling ---
# A premium, dark-mode inspired glassmorphic aesthetic
st.markdown("""
<style>
    /* Global background */
    .stApp {
        background: linear-gradient(135deg, #09090E, #1A1A2E);
        color: #E2E8F0;
    }
    
    /* Header styling */
    h1, h2, h3 {
        color: #4F46E5 !important;
        font-family: 'Inter', sans-serif;
        font-weight: 700;
        letter-spacing: -0.5px;
    }
    
    /* Customizing the main title */
    .main-title {
        background: -webkit-linear-gradient(45deg, #4F46E5, #EC4899);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-size: 3rem !important;
        padding-bottom: 20px;
        text-align: center;
    }
    
    /* Glassmorphic containers */
    .glass-container {
        background: rgba(255, 255, 255, 0.03);
        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);
        border: 1px solid rgba(255, 255, 255, 0.05);
        border-radius: 16px;
        padding: 24px;
        margin-bottom: 24px;
        box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.3);
    }
    
    /* Table styling for dataframe display */
    .stDataFrame {
        border-radius: 12px;
        overflow: hidden;
        border: 1px solid rgba(255, 255, 255, 0.1);
    }
    
    /* Upload area styling */
    .stFileUploader > div > div {
        background: rgba(79, 70, 229, 0.05);
        border: 1px dashed rgba(79, 70, 229, 0.5);
        border-radius: 12px;
        transition: all 0.3s ease;
    }
    
    .stFileUploader > div > div:hover {
        background: rgba(79, 70, 229, 0.1);
        border-color: #4F46E5;
    }
    
    /* Button styling */
    .stButton > button {
        background: linear-gradient(90deg, #4F46E5, #7C3AED);
        color: white;
        border: none;
        border-radius: 8px;
        padding: 10px 24px;
        font-weight: 600;
        transition: transform 0.2s, box-shadow 0.2s;
    }
    
    .stButton > button:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 12px rgba(79, 70, 229, 0.4);
        color: white;
    }
    
    /* Sidebar styling */
    [data-testid="stSidebar"] {
        background-color: rgba(15, 15, 26, 0.95);
        border-right: 1px solid rgba(255,255,255,0.05);
    }
</style>
""", unsafe_allow_html=True)


def main():
    # Ensure model loading
    model_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "api", "model.pkl")
    model = None
    if os.path.exists(model_path):
        with open(model_path, 'rb') as f:
            model = pickle.load(f)

    # Application Header
    st.markdown('<h1 class="main-title">Muon Physics Pipeline (Advanced) ⚛️</h1>', unsafe_allow_html=True)
    st.markdown("<p style='text-align: center; color: #94A3B8; font-size: 1.1rem;'>Level 1, 2 & 3: Upload simulation data to extract structural physics features natively and perform ML inference.</p>", unsafe_allow_html=True)
    
    # Sidebar Information
    with st.sidebar:
        st.image("https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/CERN_logo.svg/1200px-CERN_logo.svg.png", width=150)
        st.markdown("### 📊 Pipeline Status")
        if model is not None:
            st.success("System Ready & Model Loaded")
        else:
            st.warning("Model Missing - Train Model First")
        st.markdown("---")
        st.markdown("### 📋 Required Schema")
        st.markdown("""
        Ensure your CSV contains exactly these columns:
        - `Muon_ID` (int)
        - `X_in`, `Y_in` (float)
        - `X_out`, `Y_out` (float)
        """)
    
    # Main Content Area - Input Section
    st.markdown('<div class="glass-container">', unsafe_allow_html=True)
    st.markdown("## 📥 In-Box: Data Upload")
    
    col1, col2 = st.columns([2, 1])
    
    with col1:
        uploaded_file = st.file_uploader("Upload Muon Simulation Data (CSV structure)", type=['csv'])
        # If the file changes or is removed, we want to reset our state
        if uploaded_file is None:
            for key in ['show_inputs', 'features_extracted', 'view_csv']:
                if key in st.session_state:
                    st.session_state[key] = False
    
    with col2:
        st.info("ℹ️ Upload the `data/dummy_data.csv` generated by `src/generator.py` to test the system.")
    st.markdown('</div>', unsafe_allow_html=True)

    
    # Processing & Display Section
    if uploaded_file is not None:
        if st.button("🚀 Show Inputs Received", use_container_width=True):
            st.session_state['show_inputs'] = True
            
        if st.session_state.get('show_inputs', False):
            # Show a nice loading animation only if df isn't loaded yet
            if 'raw_df' not in st.session_state:
                with st.spinner("Decoding Muon Coordinate Streams..."):
                    time.sleep(1.0) # Artificial slight delay to make it feel substantial
                    st.session_state['raw_df'] = pd.read_csv(uploaded_file)
            
            try:
                df = st.session_state['raw_df']
                
                st.markdown('<div class="glass-container">', unsafe_allow_html=True)
                st.markdown("## 🔬 Raw Coordinate Telemetry")
                
                # Compute quick statistics to make dashboard richer
                total_events = len(df)
                st.success(f"Successfully loaded {total_events:,} muon tracking events.")
                
                st.markdown("### 📋 Data Preview")
                
                # Display the dataframe using Streamlit's optimized interactive table rendering
                st.dataframe(
                    df, 
                    use_container_width=True, 
                    height=400,
                    hide_index=True 
                )
                
                # Display rudimentary stats at Level 1 to show system is aware of the numbers
                st.markdown("### 📐 Preliminary Coordinate Analytics")
                c1, c2, c3, c4 = st.columns(4)
                c1.metric("Input X Variance", f"{df['X_in'].var():.2f}")
                c2.metric("Input Y Variance", f"{df['Y_in'].var():.2f}")
                c3.metric("Output X Variance", f"{df['X_out'].var():.2f}")
                c4.metric("Output Y Variance", f"{df['Y_out'].var():.2f}")
                
                st.markdown('</div>', unsafe_allow_html=True)
                
                # --- LEVEL 2: Math & Feature Extraction ---
                st.markdown('<div class="glass-container">', unsafe_allow_html=True)
                st.markdown("## 🧬 Level 2: Physics Feature Extraction")
                st.markdown("Compress the raw Cartesian coordinates into high-signal statistical moments (Variance, Kurtosis, Tail Ratio).")
                
                if st.button("Calculate Core Mathematics & Save CSV", use_container_width=True):
                    with st.spinner("Executing statistical extraction..."):
                        try:
                            # Feature Extraction natively saves to output_path
                            extract_all_features(df, output_path=FEATURES_PATH)
                            
                            st.session_state['features_extracted'] = True
                        except Exception as feat_e:
                            st.error(f"Failed feature extraction: {str(feat_e)}")
                
                if st.session_state.get('features_extracted', False) or os.path.exists(FEATURES_PATH):
                    st.success(f"Matrix condensed! Muon feature parameters accurately computed and saved to disk.")
                    st.markdown("---")
                    
                    if st.button("📂 View Output CSV Data", use_container_width=True):
                        st.session_state['view_csv'] = True
                        
                    if st.session_state.get('view_csv', False):
                        with st.spinner("Loading saved dataset..."):
                            try:
                                features_df = pd.read_csv(FEATURES_PATH)
                                
                                # Visualise new DataFrame
                                st.markdown("### 📊 Extracted Feature Database (Loaded from CSV)")
                                st.dataframe(features_df, use_container_width=True, hide_index=True)
                                
                                # Key Statistical Callouts
                                st.markdown("### 🔍 Global Extrema Found")
                                f1, f2, f3 = st.columns(3)
                                f1.metric("Highest Batch Variance", f"{features_df['Variance'].max():.4f}")
                                f2.metric("Peak Group Kurtosis", f"{features_df['Kurtosis'].max():.4f}")
                                f3.metric("Broadest Tail Distribution", f"{features_df['Tail_Ratio'].max():.4f}")
                                
                                # Enable file download
                                with open(FEATURES_PATH, 'rb') as f:
                                    st.download_button(
                                        label="💾 Download 'features.csv' for Level 3",
                                        data=f,
                                        file_name='features.csv',
                                        mime='text/csv'
                                    )
                            except Exception as e:
                                st.error(f"Could not load the extracted CSV: {str(e)}")
                            
                st.markdown('</div>', unsafe_allow_html=True)
                
                # --- LEVEL 3: ML Inference ---
                if st.session_state.get('view_csv', False):
                    st.markdown('<div class="glass-container">', unsafe_allow_html=True)
                    st.markdown("## 🤖 Level 3: Machine Learning Inference")
                    st.markdown("Run the XGBoost Classifier on the extracted statistical features to classify block composite.")
                    
                    if st.button("Run Diagnostics", use_container_width=True):
                        st.session_state['run_model'] = True
                        
                    if st.session_state.get('run_model', False):
                        if model is None:
                            st.error("⚠️ XGBoost model (model.pkl) not found. Please train the model first.")
                        else:
                            try:
                                features_df = pd.read_csv(FEATURES_PATH)
                                X = features_df[['Variance', 'Kurtosis', 'Tail_Ratio']]
                                predictions = model.predict(X)
                                
                                features_df['Prediction'] = ["LEAD" if p == 1 else "SAFE" for p in predictions]
                                
                                st.markdown("### 🎯 Inference Results by Batch")
                                st.dataframe(features_df[['Batch_ID', 'Variance', 'Kurtosis', 'Tail_Ratio', 'Prediction']], use_container_width=True, hide_index=True)
                                
                                if 1 in predictions:
                                    st.error("#### 🚨 **FINAL STATUS: LEAD DETECTED** 🚨")
                                else:
                                    st.success("#### ✅ **FINAL STATUS: BLOCK IS SAFE** ✅")
                            except Exception as ml_e:
                                st.error(f"Inference failed: {str(ml_e)}")
                    st.markdown('</div>', unsafe_allow_html=True)
                
            except Exception as e:
                st.error(f"Failed to process file. Ensure it is a valid CSV. Error: {str(e)}")
    else:
        # Placeholder state when no file uploaded
        st.markdown("""
        <div style="text-align: center; padding: 50px; color: #4b5563;">
            <p><i>Awaiting telemetry synchronization. Please upload simulation CSV.</i></p>
        </div>
        """, unsafe_allow_html=True)

if __name__ == "__main__":
    main()
